---
# HME-SWI-VSS01:
#   hostname: 10.30.20.101
#   groups: [ios]
HME-RTR-CSR01:
  hostname: 10.30.20.102
  groups: [iosxe]

# HME-NXOS-LEF01:
#   hostname: 10.10.20.21
#   groups: [nxos]
# HME-CSR-RTR01:
#   hostname: 10.10.20.22
#   groups: [iosxe]
# HME-ASA-FW01:
#   hostname: 10.10.20.23
#   groups: [asa]

# HME-C3560-SWI01:
#   hostname: 10.10.20.1
#   groups: [ios]
